### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by optikfluffel** [ColemanGariety/galileo#8] opened 2014-01-31 12:43 UTC
I just tried to sign in but it seems two factor authentication isn't working.

```
Searching the stars...
I, [2014-01-31T13:39:32.780503 #38703]  INFO -- : APICache starred: Exception raised (GET https://api.github.com/user: 401 - Must specify two-factor authentication OTP code. // See: http://developer.github.com/v3/auth#working-with-two-factor-authentication - Octokit::OneTimePasswordRequired)
W, [2014-01-31T13:39:32.781030 #38703]  WARN -- : APICache starred: Data not available in the cache or from API
```

**Comment by hofmannsven** [comment] 2014-01-31 15:37
You'll have to create a token to sign in:
» https://github.com/settings/applications

There is already an ongoing discussion here: 
» Issue https://github.com/JacksonGariety/Galileo/issues/2

**Comment by ColemanGariety** [comment] 2014-01-31 18:41
Duplicate of #2

**Closed as completed by ColemanGariety** 2014-01-31 18:41 UTC
Labels: duplicate
